%YAML:1.0

NvDSMultiObjectTracker:
  general:
    use-fetched-predictions: 1
    tracker-width: 1280
    tracker-height: 800
    gpu-id: 0
    tensor-meta-gie-id: 1
    input-tensor-meta: 1
    display-tracking-id: 1

  iou:
    # Lower accuracy tha DCF but ligter (lower latency)
    iou-threshold: 0.2

  # Low-level library for the unified tracker
  ll-lib-file: /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so