; PlatformIO Project Configuration File
; Project VESPA - Motion Node (SimpleFOC)

[env:nucleo_g431rb]
platform = ststm32
board = nucleo_g431rb
framework = arduino

lib_deps = 
    askuric/Simple FOC @ ^2.3.2
    simplefoc/SimpleFOCDrivers

build_flags = 
    -I include
    -I ../common
    -D DEBUG_MODE
    -D HAL_OPAMP_MODULE_ENABLED     ; Unlocks the STM32G431 hardware Op-Amps
    -D HAL_FDCAN_MODULE_ENABLED     ; Unlocks the STM32G431 FDCAN HAL module

upload_protocol = stlink
monitor_speed = 115200