/**
 * @file CameraInterface.h
 * @brief Low-level V4L2 wrapper for the OV9281 global shutter sensor.
 * @author Project V.E.S.P.A. Team
 * @details Manages memory-mapped (MMAP) buffers and I2C/V4L2 control injections.
 */

#ifndef VESPA_CAMERA_INTERFACE_H
#define VESPA_CAMERA_INTERFACE_H

#include <string>
#include <linux/videodev2.h>
#include <cstdint>
#include <vector>

namespace VESPA
{
    constexpr int SENSOR_WIDTH = 1280; ///< Native horizontal resolution
    constexpr int SENSOR_HEIGHT = 800; ///< Native vertical resolution
    constexpr int BUFFER_COUNT = 10;   ///< Number of ring buffers allocated in RAM

    /**
     * @struct FrameBuffer
     * @brief Maps physical memory blocks to user space for zero-copy access.
     */
    struct FrameBuffer
    {
        void *start;   ///< Pointer to the beginning of the mapped memory
        size_t length; ///< Size of the memory block in bytes
    };

    /**
     * @struct CameraSettings
     * @brief Holds optical calibration settings applied at stream start.
     */
    struct CameraSettings
    {
        int exposure = 681; ///< Sensor exposure time
        int gain = 100;     ///< Sensor analogue gain
        int h_flip = 0;     ///< Horizontal mirror toggle
        int v_flip = 0;     ///< Vertical flip toggle
    };

    /**
     * @class CameraInterface
     * @brief Interfaces with the Tegra V4L2 driver to extract raw Y8 frames.
     */
    class CameraInterface
    {
    public:
        /**
         * @brief Constructs the interface for a specific device node.
         * @param devicePath Path to the V4L2 node (e.g., "/dev/video0").
         */
        CameraInterface(const std::string &devicePath);

        /**
         * @brief Ensures stream is stopped and file descriptors are released.
         */
        ~CameraInterface();

        /**
         * @brief Opens the device, checks permissions, and requests MMAP buffers.
         * @return true if successful, false on permission/allocation failure.
         */
        bool init();

        /**
         * @brief Queues buffers to the kernel and starts the capture stream.
         * @details Applies the CameraSettings immediately after stream initiation.
         */
        void startStream();

        /**
         * @brief Stops the V4L2 capture stream.
         * @note Blocks until the kernel driver receives an End-Of-Frame (EOF) signal.
         */
        void stopStream();

        /**
         * @brief Blocks until a frame is ready, dequeues it, and yields the memory pointer.
         * @warning The caller MUST call releaseFrame() with the yielded index when finished.
         * @param timestamp_ms Reference to store the V4L2 hardware timestamp.
         * @param out_buffer Reference to a pointer that will be set to the mapped memory.
         * @param out_index Reference to store the buffer index (needed for release).
         * @return true if a frame was successfully dequeued, false on watchdog timeout.
         */
        bool captureFrame(double &timestamp_ms, uint8_t *&out_buffer, int &out_index);

        /**
         * @brief Returns a processed buffer back to the kernel queue.
         * @param index The buffer index previously yielded by captureFrame().
         */
        void releaseFrame(int index);

        /**
         * @brief Non-blocking loop that pulls all stale frames currently in the queue.
         */
        void flushQueue();

        /**
         * @brief Loads JSON optical profiles generated by the Calibration Tool.
         * @param configPath Path to the JSON configuration file.
         * @param cameraKey The key within the JSON corresponding to this sensor (e.g., "camera0").
         */
        void loadSettings(const std::string &configPath, const std::string &cameraKey);

    private:
        std::string m_devicePath;            ///< The targeted V4L2 node
        int m_fd;                            ///< V4L2 File Descriptor
        FrameBuffer m_buffers[BUFFER_COUNT]; ///< Array of mapped memory blocks
        CameraSettings m_settings;           ///< Currently loaded optical settings

        /**
         * @brief Derives the internal Tegra subdevice node (e.g., /dev/v4l-subdev0).
         */
        std::string findSubDevice(const std::string &videoDevice);

        /**
         * @brief Helper to inject specific hex commands into the sensor's DSP.
         */
        void setControl(uint32_t id, int value, const std::string &name);

        /**
         * @brief Validates execution privileges (required for DMA/I2C access).
         */
        void checkRootPermissions();
    };
}
#endif